/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.readbio.readbs.Frames;

import com.readbio.readbs.Frames.Panels.PanelSolexaQAPE;
import com.readbio.readbs.Frames.Panels.PanelSolexaQAPEBak;
import com.readbio.readbs.Frames.Panels.PanelSolexaQASE;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.io.IOException;
import java.net.URISyntaxException;

/**
 *
 * @author Shaojun
 */
public final class FrameSolexaQA extends javax.swing.JInternalFrame {

    
    GridBagLayout layout = new GridBagLayout();
    PanelSolexaQAPE SolexaQAPE = new PanelSolexaQAPE();
    PanelSolexaQASE SolexaQASE = new PanelSolexaQASE();  
    
    
    //Each internal frame comes up 30 pixels lower and to the right of the 
    //place where the previous internal frame first appeared. This functionality
    //is implemented in the MyInternalFrame class, which is the custom subclass 
    //of JInternalFrame.
    static int openFrameCount = 0;
    static final int xOffset = 10, yOffset = 10;
    private String projectDir;
    /**
     * Creates new form FrameSolexaQA
     * @param proDir
     * @throws java.net.URISyntaxException
     * @throws java.io.IOException
     */
    public FrameSolexaQA(String proDir) throws URISyntaxException, IOException {
        
      super("Document #" + (++openFrameCount), 
              true, //resizable
              true, //closable
              true, //maximizable
              true);//iconifiable
         initComponents();
        this.setProjectDir(proDir);
        SolexaQAPE = new PanelSolexaQAPE(this.getProjectDir());
        SolexaQASE = new PanelSolexaQASE(this.getProjectDir());
        DynamicPanel.setLayout(layout);
        GridBagConstraints c = new GridBagConstraints();
        c.gridx = 0 ;
        c.gridy = 0 ;
        DynamicPanel.add(SolexaQAPE, c);
        c.gridx = 0 ;
        c.gridy = 0 ;
        DynamicPanel.add(SolexaQASE, c);
        SolexaQAPE.setVisible(true);
        SolexaQASE.setVisible(false);
        setLocation(xOffset*openFrameCount, yOffset*openFrameCount);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        peRead = new javax.swing.JButton();
        seRead = new javax.swing.JButton();
        DynamicPanel = new javax.swing.JPanel();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("FrameSolexaQA");
        setToolTipText("");
        setMinimumSize(new java.awt.Dimension(0, 0));

        jPanel1.setBackground(new java.awt.Color(244, 244, 244));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11)), "Choose Run Type")); // NOI18N
        jPanel1.setInheritsPopupMenu(true);

        peRead.setText("PE Reads");
        peRead.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peReadActionPerformed(evt);
            }
        });

        seRead.setText("SE Reads");
        seRead.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seReadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(peRead)
            .addComponent(seRead)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(peRead)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(seRead)
                .addContainerGap(186, Short.MAX_VALUE))
        );

        DynamicPanel.setBackground(new java.awt.Color(244, 244, 244));
        DynamicPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("DynamicTrim & LengthSort"));

        javax.swing.GroupLayout DynamicPanelLayout = new javax.swing.GroupLayout(DynamicPanel);
        DynamicPanel.setLayout(DynamicPanelLayout);
        DynamicPanelLayout.setHorizontalGroup(
            DynamicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 477, Short.MAX_VALUE)
        );
        DynamicPanelLayout.setVerticalGroup(
            DynamicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DynamicPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(DynamicPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jPanel1.getAccessibleContext().setAccessibleDescription("Choose Run Type");

        setBounds(0, 0, 634, 413);
    }// </editor-fold>//GEN-END:initComponents

    private void peReadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peReadActionPerformed
        // TODO add your handling code here:
        SolexaQAPE.setVisible(true);
        SolexaQASE.setVisible(false);
    }//GEN-LAST:event_peReadActionPerformed

    private void seReadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seReadActionPerformed
        SolexaQAPE.setVisible(false);
        SolexaQASE.setVisible(true);
    }//GEN-LAST:event_seReadActionPerformed
    
    public String getProjectDir() {
        return projectDir;
    }

    private void setProjectDir(String temProjectDir) {
        projectDir = temProjectDir;
    }
    
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DynamicPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton peRead;
    private javax.swing.JButton seRead;
    // End of variables declaration//GEN-END:variables
}
