/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.readbio.readbs.Frames;

import com.readbio.readbs.Frames.Panels.PanelSolexaQAPE;
import com.readbio.readbs.Frames.Panels.PanelSolexaQASE;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;

/**
 *
 * @author Shaojun
 */
public class FrameSolexaQA extends javax.swing.JInternalFrame {

    //
    GridBagLayout layout = new GridBagLayout();
    PanelSolexaQAPE SolexaQAPE = new PanelSolexaQAPE();
    PanelSolexaQASE SolexaQASE = new PanelSolexaQASE();  
    
    /**
     * Creates new form FrameSolexaQA
     */
    public FrameSolexaQA() {
        initComponents();
        SolexaQAPE = new PanelSolexaQAPE();
        SolexaQASE = new PanelSolexaQASE();
        DynamicPanel.setLayout(layout);
        GridBagConstraints c = new GridBagConstraints();
        c.gridx = 0 ;
        c.gridy = 0 ;
        DynamicPanel.add(SolexaQAPE, c);
        c.gridx = 0 ;
        c.gridy = 0 ;
        DynamicPanel.add(SolexaQASE, c);
        SolexaQAPE.setVisible(true);
        SolexaQASE.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        peRead = new javax.swing.JButton();
        peRead1 = new javax.swing.JButton();
        DynamicPanel = new javax.swing.JPanel();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("FrameSolexaQA");

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 51, 0), new java.awt.Color(204, 51, 0), new java.awt.Color(204, 51, 0), new java.awt.Color(204, 51, 0)));

        peRead.setText("Paired-end Reads");
        peRead.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peReadActionPerformed(evt);
            }
        });

        peRead1.setText("Single-end Reads");
        peRead1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peRead1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(peRead)
                    .addComponent(peRead1))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(peRead)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(peRead1)
                .addContainerGap(186, Short.MAX_VALUE))
        );

        DynamicPanel.setBackground(new java.awt.Color(153, 153, 255));

        javax.swing.GroupLayout DynamicPanelLayout = new javax.swing.GroupLayout(DynamicPanel);
        DynamicPanel.setLayout(DynamicPanelLayout);
        DynamicPanelLayout.setHorizontalGroup(
            DynamicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 442, Short.MAX_VALUE)
        );
        DynamicPanelLayout.setVerticalGroup(
            DynamicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DynamicPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(DynamicPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(110, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void peReadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peReadActionPerformed
        // TODO add your handling code here:
        SolexaQAPE.setVisible(true);
        SolexaQASE.setVisible(false);
    }//GEN-LAST:event_peReadActionPerformed

    private void peRead1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peRead1ActionPerformed
        // TODO add your handling code here:
        SolexaQAPE.setVisible(false);
        SolexaQASE.setVisible(true);
    }//GEN-LAST:event_peRead1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DynamicPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton peRead;
    private javax.swing.JButton peRead1;
    // End of variables declaration//GEN-END:variables
}
